regions:
  - ap-northeast-1

blocklist:
  - "123456789012" # 管理アカウントなど削除対象外

accounts:
  "455921291711":
    filters:
      IAMUser:
        - "*"
      IAMRole:
        - "*"
      IAMGroup:
        - "*"
      IAMPolicy:
        - "*"
