regions:
  - ap-northeast-1

account-blocklist:
  - 471112978618 # 管理アカウントのリソースは間違っても消えないようにする

resource-types:
  excludes:
    - IAMUser
    - IAMUserPolicyAttachment
    - IAMUserAccessKey
    - IAMLoginProfile
    - IAMGroup
    - IAMRolePolicy
    - IAMRolePolicyAttachment
    - IAMPolicy
    - IAMSAMLProvider
accounts:
  ACCOUNT: {}
